<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>edu.harvard.hms.dbmi.avillach</groupId>
    <artifactId>pic-sure-application-stack</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>PIC-SURE Application Stack</name>
    <description>Root aggregator for all PIC-SURE components</description>


    <modules>
        <module>pic-sure</module>
        <module>pic-sure-auth-microapp</module>
        <module>pic-sure-hpds</module>
        <module>picsure-dictionary</module>
    </modules>

    <!-- Where to deploy artifacts -->
    <distributionManagement>
        <repository>
            <id>nexus-releases</id>
            <url>${maven.releases.repo}</url>
        </repository>
        <snapshotRepository>
            <id>nexus-snapshots</id>
            <url>${maven.snapshots.repo}</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <!-- Java Versioning -->
        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <!-- Nexus Repos -->
        <maven.releases.repo>http://localhost:8081/repository/maven-releases/</maven.releases.repo>
        <maven.snapshots.repo>http://localhost:8081/repository/maven-snapshots/</maven.snapshots.repo>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub HMS-DBMI Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/hms-dbmi/pic-sure</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>